language: python
dist: bionic
python:
  - "3.6"
  - "3.7"
  - "3.8"

env:
  global:
    - PIPENV_IGNORE_VIRTUALENVS=1
    - PYTHONPATH=stilus

install:
  - pip install pipenv
  - pipenv install --dev
  - export PYTHONPATH=stilus

script:
  - pipenv run flake8
  - pipenv run python setup.py test

after_success:
  - pipenv run coveralls
  - pipenv run codecov
