language: python
dist: bionic
python:
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - pip install poetry

install:
  - poetry install -v

script:
  - poetry run flake8
  - poetry run pytest --cov=stilus --cov-report html --cov-report term --cov-report term-missing tests

after_success:
  - poetry run coveralls
  - poetry run codecov
