language: python
dist: xenial
matrix:
  include:
    - python: 3.6
    - python: 3.7

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - flake8
  - python setup.py test

after_success:
  - coveralls
