sudo: false
language: python
dist: bionic
python:
  - "3.6"
  - "3.7"
  - "3.8-dev"

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - flake8
  - python setup.py test

after_success:
  - coveralls
  - codecov
