version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.6
      - test-3.7
      - test-3.8
environment: &test-environment
  PIPENV_IGNORE_VIRTUALENVS: 1
  PYTHONPATH: stilus
  PIPENV_VENV_IN_PROJECT: true
  PIPENV_QUIET: true
jobs:
  test-3.6: &test-template
    docker:
      - image: circleci/python:3.6
        environment:
          <<: *test-environment
    steps:
      - checkout
      - run: sudo pip install --upgrade pip
      - run: sudo pip install --upgrade pipenv
      - run: pipenv install --dev
      - run: pipenv run flake8 --exclude=`pipenv --venv` ~/stilus
      - run: pipenv run python setup.py test
      - run: pipenv run coveralls
      - run: pipenv run codecov
  test-3.7:
    <<: *test-template
    docker:
      - image: circleci/python:3.7
        environment:
          <<: *test-environment
  test-3.8:
    <<: *test-template
    docker:
      - image: circleci/python:3.8
        environment:
          <<: *test-environment

# CircleCI Python images available at: https://hub.docker.com/r/circleci/python/
# Read about caching dependencies: https://circleci.com/docs/2.0/caching/
# - save_cache: # cache Python dependencies using checksum of Pipfile as the cache-key
#          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
#          paths:
#            - ".venv"
#            - "/usr/local/bin"
#            - "/usr/local/lib/python3.6/site-packages"
# - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
#          path: test-results
# - store_artifacts: # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
#          path: test-results
#          destination: tr1
